#!/usr/bin/env bash

docker pull mainflux/smpp-notifier:latest
docker pull mainflux/smtp-notifier:latest
docker pull mainflux/certs:latest
docker pull mainflux/provision:latest
docker pull mainflux/mqtt:latest
docker pull mainflux/twins:latest
docker pull mainflux/opcua:latest
docker pull mainflux/bootstrap:latest
docker pull mainflux/cli:latest
docker pull mainflux/postgres-reader:latest
docker pull mainflux/timescale-writer:latest
docker pull mainflux/timescale-reader:latest
docker pull mainflux/postgres-writer:latest
docker pull mainflux/cassandra-reader:latest
docker pull mainflux/cassandra-writer:latest
docker pull mainflux/mongodb-writer:latest
docker pull mainflux/mongodb-reader:latest
docker pull mainflux/influxdb-reader:latest
docker pull mainflux/lora:latest
docker pull mainflux/influxdb-writer:latest
docker pull mainflux/ws:latest
docker pull mainflux/coap:latest
docker pull mainflux/http:latest
docker pull mainflux/things:latest
docker pull mainflux/users:latest
docker pull ghcr.io/rodneyosodo/mf-benchmark:latest
docker pull openapitools/openapi-generator-cli:latest
docker pull rodneydav/mainflux-k6-bechmark:latest
docker pull xk6-output-prometheus-remote_k6:latest
docker pull grafana/k6:master-with-browser
docker pull golang:1.20-alpine3.18
docker pull golang:1.21-alpine
docker pull registry:2
docker pull nats:2.9.21-alpine
docker pull alpine:3.18
docker pull alpine:3.18.3
docker pull ghcr.io/k3d-io/k3d-proxy:latest
docker pull ghcr.io/k3d-io/k3d-tools:latest
docker pull prom/prometheus:v2.46.0
docker pull traefik:v2.10.4
docker pull catthehacker/ubuntu:act-latest
docker pull mainflux/agent:latest
docker pull mainflux/export:latest
docker pull golang:1.20-alpine
docker pull act-elgohr-publish-docker-github-action-master-dockeraction:latest
docker pull jaegertracing/all-in-one:1.47.0
docker pull mainflux/mfxkit:latest
docker pull prom/prometheus:v2.45.0
docker pull grafana/grafana:10.0.1
docker pull grafana/k6:latest
docker pull golang:1.20.5-alpine
docker pull alpine:latest
docker pull mainflux/auth:latest
docker pull ghcr.io/hay-kot/homebox:latest
docker pull javaducky/demo-k6-operator:latest
docker pull mainflux/authn:latest
docker pull redislabs/redisinsight:latest
docker pull patrikx3/p3x-redis-ui:latest
docker pull conduktor/conduktor-platform:latest
docker pull enmotech/opengauss:latest
docker pull mainflux/callhome:latest
docker pull mainflux/call-home:latest
docker pull redis:6.2
docker pull python:3.10-slim
docker pull python:3.10-alpine
docker pull asyncapi/studio:latest
docker pull python:3.7-alpine
docker pull ghcr.io/joeferner/redis-commander:latest
docker pull grafana/grafana:9.4.7
docker pull mainflux/export13:latest
docker pull openfga/openfga:latest
docker pull grafana/grafana:latest
docker pull portainer/portainer-ee:latest
docker pull confluentinc/cp-ksqldb-server:7.3.2
docker pull confluentinc/cp-kafka-connect:7.3.2
docker pull confluentinc/cp-kafka:7.3.2
docker pull confluentinc/cp-schema-registry:7.3.2
docker pull confluentinc/cp-kafka-rest:7.3.2
docker pull confluentinc/cp-zookeeper:7.3.2
docker pull traefik:2.9.6
docker pull nginx:1.23.3-alpine
docker pull mainflux/keys:latest
docker pull prom/prometheus:latest
docker pull prom/prometheus:v2.42.0
docker pull emqx/nanomq:0.15.1
docker pull influxdb:2.5
docker pull postgres:15.1-alpine
docker pull provectuslabs/kafka-ui:latest
docker pull openzipkin/zipkin-slim:latest
docker pull openzipkin/zipkin:latest
docker pull nginx:alpine
docker pull traefik:latest
docker pull golang:1.18-alpine
docker pull golang:1.19-alpine
docker pull vault:1.12.2
docker pull portainer/portainer-ce:latest
docker pull redis:5.0-alpine
docker pull eclipse-mosquitto:latest
docker pull swaggerapi/swagger-editor:latest
docker pull gcr.io/k8s-minikube/kicbase:v0.0.36
docker pull influxdb:2.2-alpine
docker pull jaegertracing/all-in-one:1.38.0
docker pull traefik:v2.8.1
docker pull golang:1.17-alpine
docker pull rabbitmq:3.9.20-management-alpine
docker pull rabbitmq:3.9.20-management
docker pull rabbitmq:3.9.20
docker pull continuumio/miniconda3:4.12.0
docker pull mainflux/ui:latest
docker pull mainflux/mqtt:0.13.0
docker pull mainflux/vernemq:0.13.0
docker pull mainflux/vernemq:latest
docker pull mainflux/coap:0.13.0
docker pull mainflux/http:0.13.0
docker pull mainflux/things:0.13.0
docker pull mainflux/users:0.13.0
docker pull erlang:24.3.3.0-alpine
docker pull grafana/grafana:8.2.6
docker pull rancher/k3s:v1.21.7-k3s1
docker pull hello-world:latest
docker pull postgres:13.3-alpine
docker pull timescale/timescaledb:2.4.0-pg12
docker pull cassandra:3.11.10
docker pull rediscommander/redis-commander:latest
docker pull mongo:4.4.6
docker pull mongo:bionic
docker pull nats:2.2.4-alpine
docker pull influxdb:1.8.5
docker pull pashkatrick/plumber-api:latest
docker pull pashkatrick/plumber-api:http
docker pull marian/rebrow:latest
docker pull oryd/keto:v0.6.0-alpha.3
docker pull nginx:1.20.0-alpine
docker pull redis:6.2.2-alpine
docker pull influxdb:1.8.4
docker pull vault:1.6.2
docker pull eclipse-mosquitto:1.6.13
docker pull cassandra:3.11.9
docker pull mongo:4.4.3-bionic
docker pull grafana/grafana:7.3.7
docker pull johnnypark/kafka-zookeeper:latest
docker pull jaegertracing/all-in-one:1.20
docker pull golang:1.13-alpine
docker pull golang:1.14.4-alpine
docker pull containous/whoami:latest
docker pull traefik:v2.0
docker pull jaegertracing/all-in-one:1.13
docker pull postgres:10.8-alpine
docker pull nginx:1.16.0-alpine
docker pull node:10.15.1-alpine
docker pull nats:1.3.0
docker pull ridrisov/mzbench:latest
docker pull postgres:10.2-alpine
docker pull spotify/kafka:latest
