#!/usr/bin/env bash

docker pull openapitools/openapi-generator-cli:latest
docker pull xk6-output-prometheus-remote_k6:latest
docker pull golang:1.21-alpine
docker pull nats:2.9.21-alpine
docker pull alpine:3.18
docker pull alpine:3.18.3
docker pull ghcr.io/k3d-io/k3d-proxy:latest
docker pull ghcr.io/k3d-io/k3d-tools:latest
docker pull prom/prometheus:v2.46.0
docker pull traefik:v2.10.4
docker pull catthehacker/ubuntu:act-latest
docker pull golang:1.20-alpine
docker pull jaegertracing/all-in-one:1.47.0
docker pull grafana/k6:latest
docker pull alpine:latest
docker pull ghcr.io/hay-kot/homebox:latest
docker pull javaducky/demo-k6-operator:latest
docker pull redislabs/redisinsight:latest
docker pull patrikx3/p3x-redis-ui:latest
docker pull redis:6.2
docker pull python:3.10-slim
docker pull python:3.10-alpine
docker pull asyncapi/studio:latest
docker pull python:3.7-alpine
docker pull grafana/grafana:latest
docker pull portainer/portainer-ee:latest
docker pull nginx:1.23.3-alpine
docker pull prom/prometheus:latest
docker pull emqx/nanomq:0.15.1
docker pull influxdb:2.5
docker pull postgres:15.1-alpine
docker pull provectuslabs/kafka-ui:latest
docker pull nginx:alpine
docker pull traefik:latest
docker pull vault:1.12.2
docker pull portainer/portainer-ce:latest
docker pull eclipse-mosquitto:latest
docker pull swaggerapi/swagger-editor:latest
docker pull gcr.io/k8s-minikube/kicbase:v0.0.36
docker pull rabbitmq:3.9.20-management-alpine
docker pull rabbitmq:3.9.20
docker pull continuumio/miniconda3:4.12.0
docker pull erlang:24.3.3.0-alpine
docker pull rancher/k3s:v1.21.7-k3s1
docker pull hello-world:latest
docker pull postgres:13.3-alpine
docker pull timescale/timescaledb:2.4.0-pg12
docker pull cassandra:3.11.10
docker pull rediscommander/redis-commander:latest
docker pull mongo:4.4.6
docker pull vault:1.6.2
docker pull eclipse-mosquitto:1.6.13
docker pull mongo:4.4.3-bionic
docker pull grafana/grafana:7.3.7
docker pull johnnypark/kafka-zookeeper:latest
docker pull containous/whoami:latest
docker pull node:10.15.1-alpine
docker pull ridrisov/mzbench:latest
docker pull spotify/kafka:latest
