- name: Docker Setup After Install
  hosts: 127.0.0.1
  vars:
    ansible_user: rodneyosodo
  tasks:
    - name: Install Docker if not already installed
      kewlfft.aur.aur:
        name:
          - docker
          - docker-buildx
          - docker-compose
        use: yay
        state: present

    - name: Start Docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true

    - name: Add Current User to Docker Group
      ansible.builtin.shell:
        cmd: usermod -aG docker "{{ ansible_user }}"
        executable: /bin/bash
      become: yes

    - name: Restart libvirtd
      ansible.builtin.systemd_service:
        name: libvirtd
        state: restarted
        daemon_reload: true

