- name: Rust Setup After Install
  hosts: 127.0.0.1
  tasks:
    - name: Install Golang if not already installed
      kewlfft.aur.aur:
        name:
          - go
        use: yay
        state: present

    - name: Install Golang Tools
      ansible.builtin.shell: |
        go install golang.org/x/tools/cmd/godoc@latest
        go install github.com/go-delve/delve/cmd/dlv@latest
        go install github.com/google/pprof@latest
        go install golang.org/x/tools/gopls@latest
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/go-critic/go-critic/cmd/gocritic@latest
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/orlangure/gocovsh@latest
        go install github.com/Zxilly/go-size-analyzer/cmd/gsa@latest
        go install go.uber.org/nilaway/cmd/nilaway@latest
        go install github.com/oligot/go-mod-upgrade@latest
        go install github.com/vektra/mockery/v2@latest
        go install mvdan.cc/sh/v3/cmd/shfmt@latest
