
[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "On"

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
decorations = "buttonless"
dynamic_padding = false
blur = true
dynamic_title = true

[window.padding]
x = 25
y = 20

[font]
size = 12.0
# size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"


[general]
live_config_reload = true
import = ["~/.config/alacritty/gruvbox_dark.toml"]
